-- MySQL Script generated by MySQL Workbench
-- 05/12/14 15:39:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `nume client` VARCHAR(45) NULL,
  `oras client` VARCHAR(45) NULL,
  `adresa client` VARCHAR(45) NULL,
  `numar DVD inchiriate` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DVD` (
  `idDVD` INT NOT NULL,
  `numar de exemplare` INT NULL,
  `tarif inchiriere` INT NULL,
  PRIMARY KEY (`idDVD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bon` (
  `idBon` INT NOT NULL,
  `data bon inchiriere` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idBon`),
  INDEX `fk_Bon_Client1_idx` (`Client_idClient` ASC),
  CONSTRAINT `fk_Bon_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `denumire categorie film` VARCHAR(45) NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `idFilm` VARCHAR(45) NOT NULL,
  `descriere film` VARCHAR(45) NULL,
  `durata` INT NULL,
  `DVD_idDVD` INT NOT NULL,
  PRIMARY KEY (`idFilm`, `DVD_idDVD`),
  INDEX `fk_Film_DVD_idx` (`DVD_idDVD` ASC),
  CONSTRAINT `fk_Film_DVD`
    FOREIGN KEY (`DVD_idDVD`)
    REFERENCES `mydb`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bon_has_DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bon_has_DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bon_has_DVD` (
  `Bon_idBon` INT NOT NULL,
  `DVD_idDVD` INT NOT NULL,
  PRIMARY KEY (`Bon_idBon`, `DVD_idDVD`),
  INDEX `fk_Bon_has_DVD_DVD1_idx` (`DVD_idDVD` ASC),
  INDEX `fk_Bon_has_DVD_Bon1_idx` (`Bon_idBon` ASC),
  CONSTRAINT `fk_Bon_has_DVD_Bon1`
    FOREIGN KEY (`Bon_idBon`)
    REFERENCES `mydb`.`Bon` (`idBon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bon_has_DVD_DVD1`
    FOREIGN KEY (`DVD_idDVD`)
    REFERENCES `mydb`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film_has_Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film_has_Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film_has_Categorie` (
  `Film_idFilm` VARCHAR(45) NOT NULL,
  `Film_DVD_idDVD` INT NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`Film_idFilm`, `Film_DVD_idDVD`, `Categorie_idCategorie`),
  INDEX `fk_Film_has_Categorie_Categorie1_idx` (`Categorie_idCategorie` ASC),
  INDEX `fk_Film_has_Categorie_Film1_idx` (`Film_idFilm` ASC, `Film_DVD_idDVD` ASC),
  CONSTRAINT `fk_Film_has_Categorie_Film1`
    FOREIGN KEY (`Film_idFilm` , `Film_DVD_idDVD`)
    REFERENCES `mydb`.`Film` (`idFilm` , `DVD_idDVD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Categorie_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
